### ISSUE TITLE
Youtube_image.PNG is not found : 

### ISSUE THREAD

**Issue by atul120212** [nikita9604/Youtube-Downloader#2]
I got the error : 
--> file not found of name "Youtube_image.PNG" 
and
--> also PNG is not defined

**Comment by nikita9604** [comment]
YouTube_image.PNG is not added to the repo, it basically the YT logo image that is displayed on the window, which I downloaded from the internet. You can either choose to comment it or take in any image of your choice instead.
PNG not defined issue is corrected in the code.
